apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-config
  namespace: vt-it-consulting-ns
  labels:
    app: demo-k8s-config
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-k8s-config
  template:
    metadata:
      labels:
        app: demo-k8s-config
    spec:
      containers:
      - name: demo-k8s-config
        image: vtitconsulting/carvedrock.api
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: DEMO_FAREWELL
          value: "Such a sweet sorrow"
        # pass nested property
        - name: ConnectionStrings__DB
          value: "Server=notsure;Database=from K8s config Map"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: appsettings-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: appsettings-volume
        configMap:
          name: appsettings