apiVersion: v1
kind: Service
metadata:
  name: vt-it-consulting-ns
  namespace: vt-it-consulting-ns
spec:
  type: LoadBalancer
  ports:
  - port: 40010
    targetPort: 80
  selector:
    app: demo-k8s-config