apiVersion: v1
kind: Namespace
metadata:
  name: vt-it-consulting-ns
  labels:
    name: vt-it-consulting-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings
  namespace: default
data:
  appsettings.json: |-
        {
          "Logging": {
            "LogLevel": {
              "Default": "Information",
              "Microsoft": "Warning",
              "Lifetime": "Information"
            }
          },
          "ConnectionStrings": {
            "Db": "Server=notsureK8s;Database=stillnotsureK8S;User Id=sa;Password=somepassword;MultipleActiveResultSets=true;"
          },
          "SimpleProperty": "hi-there from configMap",
          "Inventory": {
            "NestedProperty": "you-are-doing-great  from configMap"
          },
          "Position": {
            "Title": "Editor from K8S  from configMap",
            "Name": "Joe Smith from K8S  from configMap",
            "ConnectionStrings": {
              "Db": "Server=ServerfromConfigMap;Database=stillnotsurefromK8S;User Id=sa;Password=somepassword;MultipleActiveResultSets=true;"
            }
          },
          "AllowedHosts": "*"
        }
