apiVersion: v1
kind: Namespace
metadata:
  name: vt-it-consulting-ns
  labels:
    name: vt-it-consulting-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings
  namespace: vt-it-consulting-ns
data:
  appsettings.json: |-
        {
          "Logging": {
            "LogLevel": {
              "Default": "Information",
              "Microsoft": "Warning",
              "Lifetime": "Information"
            }
          },
          "ConnectionStrings": {
            "Db": "Server=notsure;Database=stillnotsure;User Id=sa;Password=somepassword;MultipleActiveResultSets=true;"
          },
          "SimpleProperty": "hi-there",
          "Inventory": {
            "NestedProperty": "you-are-doing-great!"
          },
          "Position": {
            "Title": "Editor",
            "Name": "Joe Smith",
            "ConnectionStrings": {
              "Db": "Server=notsure;Database=stillnotsure;User Id=sa;Password=somepassword;MultipleActiveResultSets=true;"
            }
          },
          "AllowedHosts": "*"
        }
